let User,CustomErrorHandler;_f02‍.x([["default",()=>_f02‍.o]]);_f02‍.w("../../models",[["User",["User"],function(v){User=v}]]);_f02‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async me(req, res, next) {
    try {

      const user = await User.findOne({ _id: req.user._id });

      if (!user) {
        return next(CustomErrorHandler.notFound());
      }
      res.json(user);
    } catch (err) {}
    return next(err)
  },
};

_f02‍.d(userController);
